// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "foldersschema.h"

// Properties_t
// 

const Properties_t::ActionOptional& Properties_t::
action () const
{
  return this->action_;
}

Properties_t::ActionOptional& Properties_t::
action ()
{
  return this->action_;
}

void Properties_t::
action (const ActionType& x)
{
  this->action_.set (x);
}

void Properties_t::
action (const ActionOptional& x)
{
  this->action_ = x;
}

void Properties_t::
action (::std::unique_ptr< ActionType > x)
{
  this->action_.set (std::move (x));
}

const Properties_t::PathType& Properties_t::
path () const
{
  return this->path_.get ();
}

Properties_t::PathType& Properties_t::
path ()
{
  return this->path_.get ();
}

void Properties_t::
path (const PathType& x)
{
  this->path_.set (x);
}

void Properties_t::
path (::std::unique_ptr< PathType > x)
{
  this->path_.set (std::move (x));
}

const Properties_t::ReadOnlyType& Properties_t::
readOnly () const
{
  return this->readOnly_.get ();
}

Properties_t::ReadOnlyType& Properties_t::
readOnly ()
{
  return this->readOnly_.get ();
}

void Properties_t::
readOnly (const ReadOnlyType& x)
{
  this->readOnly_.set (x);
}

const Properties_t::ArchiveType& Properties_t::
archive () const
{
  return this->archive_.get ();
}

Properties_t::ArchiveType& Properties_t::
archive ()
{
  return this->archive_.get ();
}

void Properties_t::
archive (const ArchiveType& x)
{
  this->archive_.set (x);
}

const Properties_t::HiddenType& Properties_t::
hidden () const
{
  return this->hidden_.get ();
}

Properties_t::HiddenType& Properties_t::
hidden ()
{
  return this->hidden_.get ();
}

void Properties_t::
hidden (const HiddenType& x)
{
  this->hidden_.set (x);
}

const Properties_t::DeleteSubFoldersOptional& Properties_t::
deleteSubFolders () const
{
  return this->deleteSubFolders_;
}

Properties_t::DeleteSubFoldersOptional& Properties_t::
deleteSubFolders ()
{
  return this->deleteSubFolders_;
}

void Properties_t::
deleteSubFolders (const DeleteSubFoldersType& x)
{
  this->deleteSubFolders_.set (x);
}

void Properties_t::
deleteSubFolders (const DeleteSubFoldersOptional& x)
{
  this->deleteSubFolders_ = x;
}

const Properties_t::DeleteFilesOptional& Properties_t::
deleteFiles () const
{
  return this->deleteFiles_;
}

Properties_t::DeleteFilesOptional& Properties_t::
deleteFiles ()
{
  return this->deleteFiles_;
}

void Properties_t::
deleteFiles (const DeleteFilesType& x)
{
  this->deleteFiles_.set (x);
}

void Properties_t::
deleteFiles (const DeleteFilesOptional& x)
{
  this->deleteFiles_ = x;
}

const Properties_t::DeleteFolderOptional& Properties_t::
deleteFolder () const
{
  return this->deleteFolder_;
}

Properties_t::DeleteFolderOptional& Properties_t::
deleteFolder ()
{
  return this->deleteFolder_;
}

void Properties_t::
deleteFolder (const DeleteFolderType& x)
{
  this->deleteFolder_.set (x);
}

void Properties_t::
deleteFolder (const DeleteFolderOptional& x)
{
  this->deleteFolder_ = x;
}

const Properties_t::DeleteReadOnlyOptional& Properties_t::
deleteReadOnly () const
{
  return this->deleteReadOnly_;
}

Properties_t::DeleteReadOnlyOptional& Properties_t::
deleteReadOnly ()
{
  return this->deleteReadOnly_;
}

void Properties_t::
deleteReadOnly (const DeleteReadOnlyType& x)
{
  this->deleteReadOnly_.set (x);
}

void Properties_t::
deleteReadOnly (const DeleteReadOnlyOptional& x)
{
  this->deleteReadOnly_ = x;
}

const Properties_t::DeleteIgnoreErrorsOptional& Properties_t::
deleteIgnoreErrors () const
{
  return this->deleteIgnoreErrors_;
}

Properties_t::DeleteIgnoreErrorsOptional& Properties_t::
deleteIgnoreErrors ()
{
  return this->deleteIgnoreErrors_;
}

void Properties_t::
deleteIgnoreErrors (const DeleteIgnoreErrorsType& x)
{
  this->deleteIgnoreErrors_.set (x);
}

void Properties_t::
deleteIgnoreErrors (const DeleteIgnoreErrorsOptional& x)
{
  this->deleteIgnoreErrors_ = x;
}

const Properties_t::DisabledOptional& Properties_t::
disabled () const
{
  return this->disabled_;
}

Properties_t::DisabledOptional& Properties_t::
disabled ()
{
  return this->disabled_;
}

void Properties_t::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void Properties_t::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


// Folder_t
// 

const Folder_t::PropertiesSequence& Folder_t::
Properties () const
{
  return this->Properties_;
}

Folder_t::PropertiesSequence& Folder_t::
Properties ()
{
  return this->Properties_;
}

void Folder_t::
Properties (const PropertiesSequence& s)
{
  this->Properties_ = s;
}

const Folder_t::ClsidType& Folder_t::
clsid () const
{
  return this->clsid_.get ();
}

Folder_t::ClsidType& Folder_t::
clsid ()
{
  return this->clsid_.get ();
}

void Folder_t::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void Folder_t::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const Folder_t::NameType& Folder_t::
name () const
{
  return this->name_.get ();
}

Folder_t::NameType& Folder_t::
name ()
{
  return this->name_.get ();
}

void Folder_t::
name (const NameType& x)
{
  this->name_.set (x);
}

void Folder_t::
name (::std::unique_ptr< NameType > x)
{
  this->name_.set (std::move (x));
}

const Folder_t::StatusOptional& Folder_t::
status () const
{
  return this->status_;
}

Folder_t::StatusOptional& Folder_t::
status ()
{
  return this->status_;
}

void Folder_t::
status (const StatusType& x)
{
  this->status_.set (x);
}

void Folder_t::
status (const StatusOptional& x)
{
  this->status_ = x;
}

void Folder_t::
status (::std::unique_ptr< StatusType > x)
{
  this->status_.set (std::move (x));
}

const Folder_t::ImageOptional& Folder_t::
image () const
{
  return this->image_;
}

Folder_t::ImageOptional& Folder_t::
image ()
{
  return this->image_;
}

void Folder_t::
image (const ImageType& x)
{
  this->image_.set (x);
}

void Folder_t::
image (const ImageOptional& x)
{
  this->image_ = x;
}

const Folder_t::ChangedOptional& Folder_t::
changed () const
{
  return this->changed_;
}

Folder_t::ChangedOptional& Folder_t::
changed ()
{
  return this->changed_;
}

void Folder_t::
changed (const ChangedType& x)
{
  this->changed_.set (x);
}

void Folder_t::
changed (const ChangedOptional& x)
{
  this->changed_ = x;
}

void Folder_t::
changed (::std::unique_ptr< ChangedType > x)
{
  this->changed_.set (std::move (x));
}

const Folder_t::UidType& Folder_t::
uid () const
{
  return this->uid_.get ();
}

Folder_t::UidType& Folder_t::
uid ()
{
  return this->uid_.get ();
}

void Folder_t::
uid (const UidType& x)
{
  this->uid_.set (x);
}

void Folder_t::
uid (::std::unique_ptr< UidType > x)
{
  this->uid_.set (std::move (x));
}

const Folder_t::DescOptional& Folder_t::
desc () const
{
  return this->desc_;
}

Folder_t::DescOptional& Folder_t::
desc ()
{
  return this->desc_;
}

void Folder_t::
desc (const DescType& x)
{
  this->desc_.set (x);
}

void Folder_t::
desc (const DescOptional& x)
{
  this->desc_ = x;
}

void Folder_t::
desc (::std::unique_ptr< DescType > x)
{
  this->desc_.set (std::move (x));
}

const Folder_t::BypassErrorsOptional& Folder_t::
bypassErrors () const
{
  return this->bypassErrors_;
}

Folder_t::BypassErrorsOptional& Folder_t::
bypassErrors ()
{
  return this->bypassErrors_;
}

void Folder_t::
bypassErrors (const BypassErrorsType& x)
{
  this->bypassErrors_.set (x);
}

void Folder_t::
bypassErrors (const BypassErrorsOptional& x)
{
  this->bypassErrors_ = x;
}

const Folder_t::UserContextOptional& Folder_t::
userContext () const
{
  return this->userContext_;
}

Folder_t::UserContextOptional& Folder_t::
userContext ()
{
  return this->userContext_;
}

void Folder_t::
userContext (const UserContextType& x)
{
  this->userContext_.set (x);
}

void Folder_t::
userContext (const UserContextOptional& x)
{
  this->userContext_ = x;
}

const Folder_t::RemovePolicyOptional& Folder_t::
removePolicy () const
{
  return this->removePolicy_;
}

Folder_t::RemovePolicyOptional& Folder_t::
removePolicy ()
{
  return this->removePolicy_;
}

void Folder_t::
removePolicy (const RemovePolicyType& x)
{
  this->removePolicy_.set (x);
}

void Folder_t::
removePolicy (const RemovePolicyOptional& x)
{
  this->removePolicy_ = x;
}


// Folders
// 

const Folders::FolderSequence& Folders::
Folder () const
{
  return this->Folder_;
}

Folders::FolderSequence& Folders::
Folder ()
{
  return this->Folder_;
}

void Folders::
Folder (const FolderSequence& s)
{
  this->Folder_ = s;
}

const Folders::ClsidType& Folders::
clsid () const
{
  return this->clsid_.get ();
}

Folders::ClsidType& Folders::
clsid ()
{
  return this->clsid_.get ();
}

void Folders::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void Folders::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const Folders::DisabledOptional& Folders::
disabled () const
{
  return this->disabled_;
}

Folders::DisabledOptional& Folders::
disabled ()
{
  return this->disabled_;
}

void Folders::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void Folders::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// Properties_t
//

Properties_t::
Properties_t (const PathType& path,
              const ReadOnlyType& readOnly,
              const ArchiveType& archive,
              const HiddenType& hidden)
: ::xml_schema::Type (),
  action_ (this),
  path_ (path, this),
  readOnly_ (readOnly, this),
  archive_ (archive, this),
  hidden_ (hidden, this),
  deleteSubFolders_ (this),
  deleteFiles_ (this),
  deleteFolder_ (this),
  deleteReadOnly_ (this),
  deleteIgnoreErrors_ (this),
  disabled_ (this)
{
}

Properties_t::
Properties_t (const Properties_t& x,
              ::xml_schema::Flags f,
              ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  action_ (x.action_, f, this),
  path_ (x.path_, f, this),
  readOnly_ (x.readOnly_, f, this),
  archive_ (x.archive_, f, this),
  hidden_ (x.hidden_, f, this),
  deleteSubFolders_ (x.deleteSubFolders_, f, this),
  deleteFiles_ (x.deleteFiles_, f, this),
  deleteFolder_ (x.deleteFolder_, f, this),
  deleteReadOnly_ (x.deleteReadOnly_, f, this),
  deleteIgnoreErrors_ (x.deleteIgnoreErrors_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

Properties_t::
Properties_t (const ::xercesc::DOMElement& e,
              ::xml_schema::Flags f,
              ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  action_ (this),
  path_ (this),
  readOnly_ (this),
  archive_ (this),
  hidden_ (this),
  deleteSubFolders_ (this),
  deleteFiles_ (this),
  deleteFolder_ (this),
  deleteReadOnly_ (this),
  deleteIgnoreErrors_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void Properties_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "action" && n.namespace_ ().empty ())
    {
      this->action_.set (ActionTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "path" && n.namespace_ ().empty ())
    {
      this->path_.set (PathTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "readOnly" && n.namespace_ ().empty ())
    {
      this->readOnly_.set (ReadOnlyTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "archive" && n.namespace_ ().empty ())
    {
      this->archive_.set (ArchiveTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "hidden" && n.namespace_ ().empty ())
    {
      this->hidden_.set (HiddenTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "deleteSubFolders" && n.namespace_ ().empty ())
    {
      this->deleteSubFolders_.set (DeleteSubFoldersTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "deleteFiles" && n.namespace_ ().empty ())
    {
      this->deleteFiles_.set (DeleteFilesTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "deleteFolder" && n.namespace_ ().empty ())
    {
      this->deleteFolder_.set (DeleteFolderTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "deleteReadOnly" && n.namespace_ ().empty ())
    {
      this->deleteReadOnly_.set (DeleteReadOnlyTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "deleteIgnoreErrors" && n.namespace_ ().empty ())
    {
      this->deleteIgnoreErrors_.set (DeleteIgnoreErrorsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!path_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "path",
      "");
  }

  if (!readOnly_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "readOnly",
      "");
  }

  if (!archive_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "archive",
      "");
  }

  if (!hidden_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "hidden",
      "");
  }
}

Properties_t* Properties_t::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class Properties_t (*this, f, c);
}

Properties_t& Properties_t::
operator= (const Properties_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->action_ = x.action_;
    this->path_ = x.path_;
    this->readOnly_ = x.readOnly_;
    this->archive_ = x.archive_;
    this->hidden_ = x.hidden_;
    this->deleteSubFolders_ = x.deleteSubFolders_;
    this->deleteFiles_ = x.deleteFiles_;
    this->deleteFolder_ = x.deleteFolder_;
    this->deleteReadOnly_ = x.deleteReadOnly_;
    this->deleteIgnoreErrors_ = x.deleteIgnoreErrors_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

Properties_t::
~Properties_t ()
{
}

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, Properties_t >
_xsd_Properties_t_type_factory_init (
  "Properties_t",
  "");

// Folder_t
//

Folder_t::
Folder_t (const ClsidType& clsid,
          const NameType& name,
          const UidType& uid)
: ::xml_schema::Type (),
  Properties_ (this),
  clsid_ (clsid, this),
  name_ (name, this),
  status_ (this),
  image_ (this),
  changed_ (this),
  uid_ (uid, this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
}

Folder_t::
Folder_t (const Folder_t& x,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  Properties_ (x.Properties_, f, this),
  clsid_ (x.clsid_, f, this),
  name_ (x.name_, f, this),
  status_ (x.status_, f, this),
  image_ (x.image_, f, this),
  changed_ (x.changed_, f, this),
  uid_ (x.uid_, f, this),
  desc_ (x.desc_, f, this),
  bypassErrors_ (x.bypassErrors_, f, this),
  userContext_ (x.userContext_, f, this),
  removePolicy_ (x.removePolicy_, f, this)
{
}

Folder_t::
Folder_t (const ::xercesc::DOMElement& e,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  Properties_ (this),
  clsid_ (this),
  name_ (this),
  status_ (this),
  image_ (this),
  changed_ (this),
  uid_ (this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void Folder_t::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Properties
    //
    {
      ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
        ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
          "Properties",
          "",
          &::xsd::cxx::tree::factory_impl< PropertiesType >,
          false, true, i, n, f, this));

      if (tmp.get () != 0)
      {
        ::std::unique_ptr< PropertiesType > r (
          dynamic_cast< PropertiesType* > (tmp.get ()));

        if (r.get ())
          tmp.release ();
        else
          throw ::xsd::cxx::tree::not_derived< char > ();

        this->Properties_.push_back (::std::move (r));
        continue;
      }
    }

    break;
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      this->name_.set (NameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "status" && n.namespace_ ().empty ())
    {
      this->status_.set (StatusTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "image" && n.namespace_ ().empty ())
    {
      this->image_.set (ImageTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "changed" && n.namespace_ ().empty ())
    {
      this->changed_.set (ChangedTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "uid" && n.namespace_ ().empty ())
    {
      this->uid_.set (UidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "desc" && n.namespace_ ().empty ())
    {
      this->desc_.set (DescTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "bypassErrors" && n.namespace_ ().empty ())
    {
      this->bypassErrors_.set (BypassErrorsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "userContext" && n.namespace_ ().empty ())
    {
      this->userContext_.set (UserContextTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "removePolicy" && n.namespace_ ().empty ())
    {
      this->removePolicy_.set (RemovePolicyTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "name",
      "");
  }

  if (!uid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "uid",
      "");
  }
}

Folder_t* Folder_t::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class Folder_t (*this, f, c);
}

Folder_t& Folder_t::
operator= (const Folder_t& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->Properties_ = x.Properties_;
    this->clsid_ = x.clsid_;
    this->name_ = x.name_;
    this->status_ = x.status_;
    this->image_ = x.image_;
    this->changed_ = x.changed_;
    this->uid_ = x.uid_;
    this->desc_ = x.desc_;
    this->bypassErrors_ = x.bypassErrors_;
    this->userContext_ = x.userContext_;
    this->removePolicy_ = x.removePolicy_;
  }

  return *this;
}

Folder_t::
~Folder_t ()
{
}

static
const ::xsd::cxx::tree::type_factory_initializer< 0, char, Folder_t >
_xsd_Folder_t_type_factory_init (
  "Folder_t",
  "");

// Folders
//

Folders::
Folders (const ClsidType& clsid)
: ::xml_schema::Type (),
  Folder_ (this),
  clsid_ (clsid, this),
  disabled_ (this)
{
}

Folders::
Folders (const Folders& x,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  Folder_ (x.Folder_, f, this),
  clsid_ (x.clsid_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

Folders::
Folders (const ::xercesc::DOMElement& e,
         ::xml_schema::Flags f,
         ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  Folder_ (this),
  clsid_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void Folders::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Folder
    //
    {
      ::std::unique_ptr< ::xsd::cxx::tree::type > tmp (
        ::xsd::cxx::tree::type_factory_map_instance< 0, char > ().create (
          "Folder",
          "",
          &::xsd::cxx::tree::factory_impl< FolderType >,
          false, true, i, n, f, this));

      if (tmp.get () != 0)
      {
        ::std::unique_ptr< FolderType > r (
          dynamic_cast< FolderType* > (tmp.get ()));

        if (r.get ())
          tmp.release ();
        else
          throw ::xsd::cxx::tree::not_derived< char > ();

        this->Folder_.push_back (::std::move (r));
        continue;
      }
    }

    break;
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }
}

Folders* Folders::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class Folders (*this, f, c);
}

Folders& Folders::
operator= (const Folders& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->Folder_ = x.Folder_;
    this->clsid_ = x.clsid_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

Folders::
~Folders ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, const Properties_t& i)
{
  if (i.action ())
  {
    o << ::std::endl << "action: " << *i.action ();
  }

  o << ::std::endl << "path: " << i.path ();
  o << ::std::endl << "readOnly: " << i.readOnly ();
  o << ::std::endl << "archive: " << i.archive ();
  o << ::std::endl << "hidden: " << i.hidden ();
  if (i.deleteSubFolders ())
  {
    o << ::std::endl << "deleteSubFolders: " << *i.deleteSubFolders ();
  }

  if (i.deleteFiles ())
  {
    o << ::std::endl << "deleteFiles: " << *i.deleteFiles ();
  }

  if (i.deleteFolder ())
  {
    o << ::std::endl << "deleteFolder: " << *i.deleteFolder ();
  }

  if (i.deleteReadOnly ())
  {
    o << ::std::endl << "deleteReadOnly: " << *i.deleteReadOnly ();
  }

  if (i.deleteIgnoreErrors ())
  {
    o << ::std::endl << "deleteIgnoreErrors: " << *i.deleteIgnoreErrors ();
  }

  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, Properties_t >
_xsd_Properties_t_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const Folder_t& i)
{
  {
    ::xsd::cxx::tree::std_ostream_map< char >& om (
      ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

    for (Folder_t::PropertiesConstIterator
         b (i.Properties ().begin ()), e (i.Properties ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "Properties: ";
      om.insert (o, *b);
    }
  }

  o << ::std::endl << "clsid: " << i.clsid ();
  o << ::std::endl << "name: " << i.name ();
  if (i.status ())
  {
    o << ::std::endl << "status: " << *i.status ();
  }

  if (i.image ())
  {
    o << ::std::endl << "image: " << *i.image ();
  }

  if (i.changed ())
  {
    o << ::std::endl << "changed: " << *i.changed ();
  }

  o << ::std::endl << "uid: " << i.uid ();
  if (i.desc ())
  {
    o << ::std::endl << "desc: " << *i.desc ();
  }

  if (i.bypassErrors ())
  {
    o << ::std::endl << "bypassErrors: " << *i.bypassErrors ();
  }

  if (i.userContext ())
  {
    o << ::std::endl << "userContext: " << *i.userContext ();
  }

  if (i.removePolicy ())
  {
    o << ::std::endl << "removePolicy: " << *i.removePolicy ();
  }

  return o;
}

static
const ::xsd::cxx::tree::std_ostream_initializer< 0, char, Folder_t >
_xsd_Folder_t_std_ostream_init;

::std::ostream&
operator<< (::std::ostream& o, const Folders& i)
{
  {
    ::xsd::cxx::tree::std_ostream_map< char >& om (
      ::xsd::cxx::tree::std_ostream_map_instance< 0, char > ());

    for (Folders::FolderConstIterator
         b (i.Folder ().begin ()), e (i.Folder ().end ());
         b != e; ++b)
    {
      o << ::std::endl << "Folder: ";
      om.insert (o, *b);
    }
  }

  o << ::std::endl << "clsid: " << i.clsid ();
  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::Folders >
Folders_ (const ::std::string& u,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (const ::std::string& u,
          ::xml_schema::ErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (const ::std::string& u,
          ::xercesc::DOMErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Folders_ (isrc, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          ::xml_schema::ErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Folders_ (isrc, h, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          ::xercesc::DOMErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::Folders_ (isrc, h, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          const ::std::string& sid,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Folders_ (isrc, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          const ::std::string& sid,
          ::xml_schema::ErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Folders_ (isrc, h, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::std::istream& is,
          const ::std::string& sid,
          ::xercesc::DOMErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::Folders_ (isrc, h, f, p);
}

::std::unique_ptr< ::Folders >
Folders_ (::xercesc::InputSource& i,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (::xercesc::InputSource& i,
          ::xml_schema::ErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (::xercesc::InputSource& i,
          ::xercesc::DOMErrorHandler& h,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::Folders > (
    ::Folders_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::Folders >
Folders_ (const ::xercesc::DOMDocument& doc,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::Folders > (
      ::Folders_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "Folders" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Folders > r (
      ::xsd::cxx::tree::traits< ::Folders, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Folders",
    "");
}

::std::unique_ptr< ::Folders >
Folders_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
          ::xml_schema::Flags f,
          const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "Folders" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::Folders > r (
      ::xsd::cxx::tree::traits< ::Folders, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "Folders",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

