// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "sharesschema.h"

// NetworkShareSettings
// 

const NetworkShareSettings::NetShareType& NetworkShareSettings::
NetShare () const
{
  return this->NetShare_.get ();
}

NetworkShareSettings::NetShareType& NetworkShareSettings::
NetShare ()
{
  return this->NetShare_.get ();
}

void NetworkShareSettings::
NetShare (const NetShareType& x)
{
  this->NetShare_.set (x);
}

void NetworkShareSettings::
NetShare (::std::unique_ptr< NetShareType > x)
{
  this->NetShare_.set (std::move (x));
}

const NetworkShareSettings::ClsidType& NetworkShareSettings::
clsid () const
{
  return this->clsid_.get ();
}

NetworkShareSettings::ClsidType& NetworkShareSettings::
clsid ()
{
  return this->clsid_.get ();
}

void NetworkShareSettings::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void NetworkShareSettings::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const NetworkShareSettings::DisabledOptional& NetworkShareSettings::
disabled () const
{
  return this->disabled_;
}

NetworkShareSettings::DisabledOptional& NetworkShareSettings::
disabled ()
{
  return this->disabled_;
}

void NetworkShareSettings::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void NetworkShareSettings::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


// NetShare
// 

const NetShare::PropertiesType& NetShare::
Properties () const
{
  return this->Properties_.get ();
}

NetShare::PropertiesType& NetShare::
Properties ()
{
  return this->Properties_.get ();
}

void NetShare::
Properties (const PropertiesType& x)
{
  this->Properties_.set (x);
}

void NetShare::
Properties (::std::unique_ptr< PropertiesType > x)
{
  this->Properties_.set (std::move (x));
}

const NetShare::ClsidType& NetShare::
clsid () const
{
  return this->clsid_.get ();
}

NetShare::ClsidType& NetShare::
clsid ()
{
  return this->clsid_.get ();
}

void NetShare::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void NetShare::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const NetShare::ImageOptional& NetShare::
image () const
{
  return this->image_;
}

NetShare::ImageOptional& NetShare::
image ()
{
  return this->image_;
}

void NetShare::
image (const ImageType& x)
{
  this->image_.set (x);
}

void NetShare::
image (const ImageOptional& x)
{
  this->image_ = x;
}

const NetShare::NameType& NetShare::
name () const
{
  return this->name_.get ();
}

NetShare::NameType& NetShare::
name ()
{
  return this->name_.get ();
}

void NetShare::
name (const NameType& x)
{
  this->name_.set (x);
}

void NetShare::
name (::std::unique_ptr< NameType > x)
{
  this->name_.set (std::move (x));
}

const NetShare::ChangedOptional& NetShare::
changed () const
{
  return this->changed_;
}

NetShare::ChangedOptional& NetShare::
changed ()
{
  return this->changed_;
}

void NetShare::
changed (const ChangedType& x)
{
  this->changed_.set (x);
}

void NetShare::
changed (const ChangedOptional& x)
{
  this->changed_ = x;
}

void NetShare::
changed (::std::unique_ptr< ChangedType > x)
{
  this->changed_.set (std::move (x));
}

const NetShare::UidType& NetShare::
uid () const
{
  return this->uid_.get ();
}

NetShare::UidType& NetShare::
uid ()
{
  return this->uid_.get ();
}

void NetShare::
uid (const UidType& x)
{
  this->uid_.set (x);
}

void NetShare::
uid (::std::unique_ptr< UidType > x)
{
  this->uid_.set (std::move (x));
}

const NetShare::DescOptional& NetShare::
desc () const
{
  return this->desc_;
}

NetShare::DescOptional& NetShare::
desc ()
{
  return this->desc_;
}

void NetShare::
desc (const DescType& x)
{
  this->desc_.set (x);
}

void NetShare::
desc (const DescOptional& x)
{
  this->desc_ = x;
}

void NetShare::
desc (::std::unique_ptr< DescType > x)
{
  this->desc_.set (std::move (x));
}

const NetShare::BypassErrorsOptional& NetShare::
bypassErrors () const
{
  return this->bypassErrors_;
}

NetShare::BypassErrorsOptional& NetShare::
bypassErrors ()
{
  return this->bypassErrors_;
}

void NetShare::
bypassErrors (const BypassErrorsType& x)
{
  this->bypassErrors_.set (x);
}

void NetShare::
bypassErrors (const BypassErrorsOptional& x)
{
  this->bypassErrors_ = x;
}

const NetShare::UserContextOptional& NetShare::
userContext () const
{
  return this->userContext_;
}

NetShare::UserContextOptional& NetShare::
userContext ()
{
  return this->userContext_;
}

void NetShare::
userContext (const UserContextType& x)
{
  this->userContext_.set (x);
}

void NetShare::
userContext (const UserContextOptional& x)
{
  this->userContext_ = x;
}

const NetShare::RemovePolicyOptional& NetShare::
removePolicy () const
{
  return this->removePolicy_;
}

NetShare::RemovePolicyOptional& NetShare::
removePolicy ()
{
  return this->removePolicy_;
}

void NetShare::
removePolicy (const RemovePolicyType& x)
{
  this->removePolicy_.set (x);
}

void NetShare::
removePolicy (const RemovePolicyOptional& x)
{
  this->removePolicy_ = x;
}


// Properties
// 

const Properties::ActionOptional& Properties::
action () const
{
  return this->action_;
}

Properties::ActionOptional& Properties::
action ()
{
  return this->action_;
}

void Properties::
action (const ActionType& x)
{
  this->action_.set (x);
}

void Properties::
action (const ActionOptional& x)
{
  this->action_ = x;
}

void Properties::
action (::std::unique_ptr< ActionType > x)
{
  this->action_.set (std::move (x));
}

const Properties::NameType& Properties::
name () const
{
  return this->name_.get ();
}

Properties::NameType& Properties::
name ()
{
  return this->name_.get ();
}

void Properties::
name (const NameType& x)
{
  this->name_.set (x);
}

void Properties::
name (::std::unique_ptr< NameType > x)
{
  this->name_.set (std::move (x));
}

const Properties::PathType& Properties::
path () const
{
  return this->path_.get ();
}

Properties::PathType& Properties::
path ()
{
  return this->path_.get ();
}

void Properties::
path (const PathType& x)
{
  this->path_.set (x);
}

void Properties::
path (::std::unique_ptr< PathType > x)
{
  this->path_.set (std::move (x));
}

const Properties::CommentType& Properties::
comment () const
{
  return this->comment_.get ();
}

Properties::CommentType& Properties::
comment ()
{
  return this->comment_.get ();
}

void Properties::
comment (const CommentType& x)
{
  this->comment_.set (x);
}

void Properties::
comment (::std::unique_ptr< CommentType > x)
{
  this->comment_.set (std::move (x));
}

const Properties::AllRegularOptional& Properties::
allRegular () const
{
  return this->allRegular_;
}

Properties::AllRegularOptional& Properties::
allRegular ()
{
  return this->allRegular_;
}

void Properties::
allRegular (const AllRegularType& x)
{
  this->allRegular_.set (x);
}

void Properties::
allRegular (const AllRegularOptional& x)
{
  this->allRegular_ = x;
}

const Properties::AllHiddenOptional& Properties::
allHidden () const
{
  return this->allHidden_;
}

Properties::AllHiddenOptional& Properties::
allHidden ()
{
  return this->allHidden_;
}

void Properties::
allHidden (const AllHiddenType& x)
{
  this->allHidden_.set (x);
}

void Properties::
allHidden (const AllHiddenOptional& x)
{
  this->allHidden_ = x;
}

const Properties::AllAdminDriveOptional& Properties::
allAdminDrive () const
{
  return this->allAdminDrive_;
}

Properties::AllAdminDriveOptional& Properties::
allAdminDrive ()
{
  return this->allAdminDrive_;
}

void Properties::
allAdminDrive (const AllAdminDriveType& x)
{
  this->allAdminDrive_.set (x);
}

void Properties::
allAdminDrive (const AllAdminDriveOptional& x)
{
  this->allAdminDrive_ = x;
}

const Properties::LimitUsersOptional& Properties::
limitUsers () const
{
  return this->limitUsers_;
}

Properties::LimitUsersOptional& Properties::
limitUsers ()
{
  return this->limitUsers_;
}

void Properties::
limitUsers (const LimitUsersType& x)
{
  this->limitUsers_.set (x);
}

void Properties::
limitUsers (const LimitUsersOptional& x)
{
  this->limitUsers_ = x;
}

void Properties::
limitUsers (::std::unique_ptr< LimitUsersType > x)
{
  this->limitUsers_.set (std::move (x));
}

const Properties::AbeOptional& Properties::
abe () const
{
  return this->abe_;
}

Properties::AbeOptional& Properties::
abe ()
{
  return this->abe_;
}

void Properties::
abe (const AbeType& x)
{
  this->abe_.set (x);
}

void Properties::
abe (const AbeOptional& x)
{
  this->abe_ = x;
}

void Properties::
abe (::std::unique_ptr< AbeType > x)
{
  this->abe_.set (std::move (x));
}

const Properties::UserLimitOptional& Properties::
userLimit () const
{
  return this->userLimit_;
}

Properties::UserLimitOptional& Properties::
userLimit ()
{
  return this->userLimit_;
}

void Properties::
userLimit (const UserLimitType& x)
{
  this->userLimit_.set (x);
}

void Properties::
userLimit (const UserLimitOptional& x)
{
  this->userLimit_ = x;
}

const Properties::DisabledOptional& Properties::
disabled () const
{
  return this->disabled_;
}

Properties::DisabledOptional& Properties::
disabled ()
{
  return this->disabled_;
}

void Properties::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void Properties::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// NetworkShareSettings
//

NetworkShareSettings::
NetworkShareSettings (const NetShareType& NetShare,
                      const ClsidType& clsid)
: ::xml_schema::Type (),
  NetShare_ (NetShare, this),
  clsid_ (clsid, this),
  disabled_ (this)
{
}

NetworkShareSettings::
NetworkShareSettings (::std::unique_ptr< NetShareType > NetShare,
                      const ClsidType& clsid)
: ::xml_schema::Type (),
  NetShare_ (std::move (NetShare), this),
  clsid_ (clsid, this),
  disabled_ (this)
{
}

NetworkShareSettings::
NetworkShareSettings (const NetworkShareSettings& x,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  NetShare_ (x.NetShare_, f, this),
  clsid_ (x.clsid_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

NetworkShareSettings::
NetworkShareSettings (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  NetShare_ (this),
  clsid_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void NetworkShareSettings::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // NetShare
    //
    if (n.name () == "NetShare" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< NetShareType > r (
        NetShareTraits::create (i, f, this));

      if (!NetShare_.present ())
      {
        this->NetShare_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!NetShare_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "NetShare",
      "");
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }
}

NetworkShareSettings* NetworkShareSettings::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class NetworkShareSettings (*this, f, c);
}

NetworkShareSettings& NetworkShareSettings::
operator= (const NetworkShareSettings& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->NetShare_ = x.NetShare_;
    this->clsid_ = x.clsid_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

NetworkShareSettings::
~NetworkShareSettings ()
{
}

// NetShare
//

NetShare::
NetShare (const PropertiesType& Properties,
          const ClsidType& clsid,
          const NameType& name,
          const UidType& uid)
: ::xml_schema::Type (),
  Properties_ (Properties, this),
  clsid_ (clsid, this),
  image_ (this),
  name_ (name, this),
  changed_ (this),
  uid_ (uid, this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
}

NetShare::
NetShare (::std::unique_ptr< PropertiesType > Properties,
          const ClsidType& clsid,
          const NameType& name,
          const UidType& uid)
: ::xml_schema::Type (),
  Properties_ (std::move (Properties), this),
  clsid_ (clsid, this),
  image_ (this),
  name_ (name, this),
  changed_ (this),
  uid_ (uid, this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
}

NetShare::
NetShare (const NetShare& x,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  Properties_ (x.Properties_, f, this),
  clsid_ (x.clsid_, f, this),
  image_ (x.image_, f, this),
  name_ (x.name_, f, this),
  changed_ (x.changed_, f, this),
  uid_ (x.uid_, f, this),
  desc_ (x.desc_, f, this),
  bypassErrors_ (x.bypassErrors_, f, this),
  userContext_ (x.userContext_, f, this),
  removePolicy_ (x.removePolicy_, f, this)
{
}

NetShare::
NetShare (const ::xercesc::DOMElement& e,
          ::xml_schema::Flags f,
          ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  Properties_ (this),
  clsid_ (this),
  image_ (this),
  name_ (this),
  changed_ (this),
  uid_ (this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void NetShare::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Properties
    //
    if (n.name () == "Properties" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< PropertiesType > r (
        PropertiesTraits::create (i, f, this));

      if (!Properties_.present ())
      {
        this->Properties_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!Properties_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Properties",
      "");
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "image" && n.namespace_ ().empty ())
    {
      this->image_.set (ImageTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      this->name_.set (NameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "changed" && n.namespace_ ().empty ())
    {
      this->changed_.set (ChangedTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "uid" && n.namespace_ ().empty ())
    {
      this->uid_.set (UidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "desc" && n.namespace_ ().empty ())
    {
      this->desc_.set (DescTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "bypassErrors" && n.namespace_ ().empty ())
    {
      this->bypassErrors_.set (BypassErrorsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "userContext" && n.namespace_ ().empty ())
    {
      this->userContext_.set (UserContextTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "removePolicy" && n.namespace_ ().empty ())
    {
      this->removePolicy_.set (RemovePolicyTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "name",
      "");
  }

  if (!uid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "uid",
      "");
  }
}

NetShare* NetShare::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class NetShare (*this, f, c);
}

NetShare& NetShare::
operator= (const NetShare& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->Properties_ = x.Properties_;
    this->clsid_ = x.clsid_;
    this->image_ = x.image_;
    this->name_ = x.name_;
    this->changed_ = x.changed_;
    this->uid_ = x.uid_;
    this->desc_ = x.desc_;
    this->bypassErrors_ = x.bypassErrors_;
    this->userContext_ = x.userContext_;
    this->removePolicy_ = x.removePolicy_;
  }

  return *this;
}

NetShare::
~NetShare ()
{
}

// Properties
//

Properties::
Properties (const NameType& name,
            const PathType& path,
            const CommentType& comment)
: ::xml_schema::Type (),
  action_ (this),
  name_ (name, this),
  path_ (path, this),
  comment_ (comment, this),
  allRegular_ (this),
  allHidden_ (this),
  allAdminDrive_ (this),
  limitUsers_ (this),
  abe_ (this),
  userLimit_ (this),
  disabled_ (this)
{
}

Properties::
Properties (const Properties& x,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  action_ (x.action_, f, this),
  name_ (x.name_, f, this),
  path_ (x.path_, f, this),
  comment_ (x.comment_, f, this),
  allRegular_ (x.allRegular_, f, this),
  allHidden_ (x.allHidden_, f, this),
  allAdminDrive_ (x.allAdminDrive_, f, this),
  limitUsers_ (x.limitUsers_, f, this),
  abe_ (x.abe_, f, this),
  userLimit_ (x.userLimit_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

Properties::
Properties (const ::xercesc::DOMElement& e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  action_ (this),
  name_ (this),
  path_ (this),
  comment_ (this),
  allRegular_ (this),
  allHidden_ (this),
  allAdminDrive_ (this),
  limitUsers_ (this),
  abe_ (this),
  userLimit_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void Properties::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "action" && n.namespace_ ().empty ())
    {
      this->action_.set (ActionTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      this->name_.set (NameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "path" && n.namespace_ ().empty ())
    {
      this->path_.set (PathTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "comment" && n.namespace_ ().empty ())
    {
      this->comment_.set (CommentTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "allRegular" && n.namespace_ ().empty ())
    {
      this->allRegular_.set (AllRegularTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "allHidden" && n.namespace_ ().empty ())
    {
      this->allHidden_.set (AllHiddenTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "allAdminDrive" && n.namespace_ ().empty ())
    {
      this->allAdminDrive_.set (AllAdminDriveTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "limitUsers" && n.namespace_ ().empty ())
    {
      this->limitUsers_.set (LimitUsersTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "abe" && n.namespace_ ().empty ())
    {
      this->abe_.set (AbeTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "userLimit" && n.namespace_ ().empty ())
    {
      this->userLimit_.set (UserLimitTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "name",
      "");
  }

  if (!path_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "path",
      "");
  }

  if (!comment_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "comment",
      "");
  }
}

Properties* Properties::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class Properties (*this, f, c);
}

Properties& Properties::
operator= (const Properties& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->action_ = x.action_;
    this->name_ = x.name_;
    this->path_ = x.path_;
    this->comment_ = x.comment_;
    this->allRegular_ = x.allRegular_;
    this->allHidden_ = x.allHidden_;
    this->allAdminDrive_ = x.allAdminDrive_;
    this->limitUsers_ = x.limitUsers_;
    this->abe_ = x.abe_;
    this->userLimit_ = x.userLimit_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

Properties::
~Properties ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, const NetworkShareSettings& i)
{
  o << ::std::endl << "NetShare: " << i.NetShare ();
  o << ::std::endl << "clsid: " << i.clsid ();
  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const NetShare& i)
{
  o << ::std::endl << "Properties: " << i.Properties ();
  o << ::std::endl << "clsid: " << i.clsid ();
  if (i.image ())
  {
    o << ::std::endl << "image: " << *i.image ();
  }

  o << ::std::endl << "name: " << i.name ();
  if (i.changed ())
  {
    o << ::std::endl << "changed: " << *i.changed ();
  }

  o << ::std::endl << "uid: " << i.uid ();
  if (i.desc ())
  {
    o << ::std::endl << "desc: " << *i.desc ();
  }

  if (i.bypassErrors ())
  {
    o << ::std::endl << "bypassErrors: " << *i.bypassErrors ();
  }

  if (i.userContext ())
  {
    o << ::std::endl << "userContext: " << *i.userContext ();
  }

  if (i.removePolicy ())
  {
    o << ::std::endl << "removePolicy: " << *i.removePolicy ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const Properties& i)
{
  if (i.action ())
  {
    o << ::std::endl << "action: " << *i.action ();
  }

  o << ::std::endl << "name: " << i.name ();
  o << ::std::endl << "path: " << i.path ();
  o << ::std::endl << "comment: " << i.comment ();
  if (i.allRegular ())
  {
    o << ::std::endl << "allRegular: " << *i.allRegular ();
  }

  if (i.allHidden ())
  {
    o << ::std::endl << "allHidden: " << *i.allHidden ();
  }

  if (i.allAdminDrive ())
  {
    o << ::std::endl << "allAdminDrive: " << *i.allAdminDrive ();
  }

  if (i.limitUsers ())
  {
    o << ::std::endl << "limitUsers: " << *i.limitUsers ();
  }

  if (i.abe ())
  {
    o << ::std::endl << "abe: " << *i.abe ();
  }

  if (i.userLimit ())
  {
    o << ::std::endl << "userLimit: " << *i.userLimit ();
  }

  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (const ::std::string& u,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (const ::std::string& u,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (const ::std::string& u,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::NetworkShareSettings_ (isrc, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::NetworkShareSettings_ (isrc, h, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::NetworkShareSettings_ (isrc, h, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::NetworkShareSettings_ (isrc, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::NetworkShareSettings_ (isrc, h, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::NetworkShareSettings_ (isrc, h, f, p);
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::xercesc::InputSource& i,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::xercesc::InputSource& i,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::xercesc::InputSource& i,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::NetworkShareSettings > (
    ::NetworkShareSettings_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (const ::xercesc::DOMDocument& doc,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::NetworkShareSettings > (
      ::NetworkShareSettings_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "NetworkShareSettings" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::NetworkShareSettings > r (
      ::xsd::cxx::tree::traits< ::NetworkShareSettings, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "NetworkShareSettings",
    "");
}

::std::unique_ptr< ::NetworkShareSettings >
NetworkShareSettings_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "NetworkShareSettings" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::NetworkShareSettings > r (
      ::xsd::cxx::tree::traits< ::NetworkShareSettings, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "NetworkShareSettings",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

