.\" Manpage for gpui.
.\" Contact august@altlinux.org to correct errors or typos.
.TH man 1 "10 Nov 2022" "0.2.17" "gpui man page"
.SH NAME
gpui-main \- редактирует шаблоны групповых политик
.SH SYNOPSIS
gpui-main [-p путь к политике] [-b путь к admx файлам] [-n имя политики для отображения] [-h | --help] [-v | --version]
.SH DESCRIPTION
gpui-main это программа для управления шаблонами групповой политики.
.SH OPTIONS
.TP
.if  !'po4a'hide' .BR \-p
Позволяет указать путь к шаблону групповой политики, который нужно редактировать.
.TP
.if  !'po4a'hide' .BR \-b
Позволяет указать путь для загрузки admx файлов.
.TP
.if  !'po4a'hide' .BR \-h ", " \-\-help
Показать справочное сообщение и закончить работу.
.TP
.if  !'po4a'hide' .BR \-v ", " \-\-version
Показать информацию о версии.
.SH SEE ALSO
.SH BUGS
Утилита находится в состоянии активной разработки и может содержать неопределенное количество различных ошибок.
.SH AUTHOR
August (august@altlinux.org)
