// Copyright (c) 2005-2017 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "variablesschema.h"

// EnvironmentVariables
// 

const EnvironmentVariables::EnvironmentVariableSequence& EnvironmentVariables::
EnvironmentVariable () const
{
  return this->EnvironmentVariable_;
}

EnvironmentVariables::EnvironmentVariableSequence& EnvironmentVariables::
EnvironmentVariable ()
{
  return this->EnvironmentVariable_;
}

void EnvironmentVariables::
EnvironmentVariable (const EnvironmentVariableSequence& s)
{
  this->EnvironmentVariable_ = s;
}

const EnvironmentVariables::ClsidType& EnvironmentVariables::
clsid () const
{
  return this->clsid_.get ();
}

EnvironmentVariables::ClsidType& EnvironmentVariables::
clsid ()
{
  return this->clsid_.get ();
}

void EnvironmentVariables::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void EnvironmentVariables::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const EnvironmentVariables::DisabledOptional& EnvironmentVariables::
disabled () const
{
  return this->disabled_;
}

EnvironmentVariables::DisabledOptional& EnvironmentVariables::
disabled ()
{
  return this->disabled_;
}

void EnvironmentVariables::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void EnvironmentVariables::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


// EnvironmentVariable
// 

const EnvironmentVariable::PropertiesType& EnvironmentVariable::
Properties () const
{
  return this->Properties_.get ();
}

EnvironmentVariable::PropertiesType& EnvironmentVariable::
Properties ()
{
  return this->Properties_.get ();
}

void EnvironmentVariable::
Properties (const PropertiesType& x)
{
  this->Properties_.set (x);
}

void EnvironmentVariable::
Properties (::std::unique_ptr< PropertiesType > x)
{
  this->Properties_.set (std::move (x));
}

const EnvironmentVariable::ClsidType& EnvironmentVariable::
clsid () const
{
  return this->clsid_.get ();
}

EnvironmentVariable::ClsidType& EnvironmentVariable::
clsid ()
{
  return this->clsid_.get ();
}

void EnvironmentVariable::
clsid (const ClsidType& x)
{
  this->clsid_.set (x);
}

void EnvironmentVariable::
clsid (::std::unique_ptr< ClsidType > x)
{
  this->clsid_.set (std::move (x));
}

const EnvironmentVariable::NameType& EnvironmentVariable::
name () const
{
  return this->name_.get ();
}

EnvironmentVariable::NameType& EnvironmentVariable::
name ()
{
  return this->name_.get ();
}

void EnvironmentVariable::
name (const NameType& x)
{
  this->name_.set (x);
}

void EnvironmentVariable::
name (::std::unique_ptr< NameType > x)
{
  this->name_.set (std::move (x));
}

const EnvironmentVariable::ImageOptional& EnvironmentVariable::
image () const
{
  return this->image_;
}

EnvironmentVariable::ImageOptional& EnvironmentVariable::
image ()
{
  return this->image_;
}

void EnvironmentVariable::
image (const ImageType& x)
{
  this->image_.set (x);
}

void EnvironmentVariable::
image (const ImageOptional& x)
{
  this->image_ = x;
}

const EnvironmentVariable::ChangedOptional& EnvironmentVariable::
changed () const
{
  return this->changed_;
}

EnvironmentVariable::ChangedOptional& EnvironmentVariable::
changed ()
{
  return this->changed_;
}

void EnvironmentVariable::
changed (const ChangedType& x)
{
  this->changed_.set (x);
}

void EnvironmentVariable::
changed (const ChangedOptional& x)
{
  this->changed_ = x;
}

void EnvironmentVariable::
changed (::std::unique_ptr< ChangedType > x)
{
  this->changed_.set (std::move (x));
}

const EnvironmentVariable::UidType& EnvironmentVariable::
uid () const
{
  return this->uid_.get ();
}

EnvironmentVariable::UidType& EnvironmentVariable::
uid ()
{
  return this->uid_.get ();
}

void EnvironmentVariable::
uid (const UidType& x)
{
  this->uid_.set (x);
}

void EnvironmentVariable::
uid (::std::unique_ptr< UidType > x)
{
  this->uid_.set (std::move (x));
}

const EnvironmentVariable::DescOptional& EnvironmentVariable::
desc () const
{
  return this->desc_;
}

EnvironmentVariable::DescOptional& EnvironmentVariable::
desc ()
{
  return this->desc_;
}

void EnvironmentVariable::
desc (const DescType& x)
{
  this->desc_.set (x);
}

void EnvironmentVariable::
desc (const DescOptional& x)
{
  this->desc_ = x;
}

void EnvironmentVariable::
desc (::std::unique_ptr< DescType > x)
{
  this->desc_.set (std::move (x));
}

const EnvironmentVariable::BypassErrorsOptional& EnvironmentVariable::
bypassErrors () const
{
  return this->bypassErrors_;
}

EnvironmentVariable::BypassErrorsOptional& EnvironmentVariable::
bypassErrors ()
{
  return this->bypassErrors_;
}

void EnvironmentVariable::
bypassErrors (const BypassErrorsType& x)
{
  this->bypassErrors_.set (x);
}

void EnvironmentVariable::
bypassErrors (const BypassErrorsOptional& x)
{
  this->bypassErrors_ = x;
}

const EnvironmentVariable::UserContextOptional& EnvironmentVariable::
userContext () const
{
  return this->userContext_;
}

EnvironmentVariable::UserContextOptional& EnvironmentVariable::
userContext ()
{
  return this->userContext_;
}

void EnvironmentVariable::
userContext (const UserContextType& x)
{
  this->userContext_.set (x);
}

void EnvironmentVariable::
userContext (const UserContextOptional& x)
{
  this->userContext_ = x;
}

const EnvironmentVariable::RemovePolicyOptional& EnvironmentVariable::
removePolicy () const
{
  return this->removePolicy_;
}

EnvironmentVariable::RemovePolicyOptional& EnvironmentVariable::
removePolicy ()
{
  return this->removePolicy_;
}

void EnvironmentVariable::
removePolicy (const RemovePolicyType& x)
{
  this->removePolicy_.set (x);
}

void EnvironmentVariable::
removePolicy (const RemovePolicyOptional& x)
{
  this->removePolicy_ = x;
}


// Properties
// 

const Properties::ActionOptional& Properties::
action () const
{
  return this->action_;
}

Properties::ActionOptional& Properties::
action ()
{
  return this->action_;
}

void Properties::
action (const ActionType& x)
{
  this->action_.set (x);
}

void Properties::
action (const ActionOptional& x)
{
  this->action_ = x;
}

void Properties::
action (::std::unique_ptr< ActionType > x)
{
  this->action_.set (std::move (x));
}

const Properties::NameType& Properties::
name () const
{
  return this->name_.get ();
}

Properties::NameType& Properties::
name ()
{
  return this->name_.get ();
}

void Properties::
name (const NameType& x)
{
  this->name_.set (x);
}

void Properties::
name (::std::unique_ptr< NameType > x)
{
  this->name_.set (std::move (x));
}

const Properties::ValueType& Properties::
value () const
{
  return this->value_.get ();
}

Properties::ValueType& Properties::
value ()
{
  return this->value_.get ();
}

void Properties::
value (const ValueType& x)
{
  this->value_.set (x);
}

void Properties::
value (::std::unique_ptr< ValueType > x)
{
  this->value_.set (std::move (x));
}

const Properties::UserOptional& Properties::
user () const
{
  return this->user_;
}

Properties::UserOptional& Properties::
user ()
{
  return this->user_;
}

void Properties::
user (const UserType& x)
{
  this->user_.set (x);
}

void Properties::
user (const UserOptional& x)
{
  this->user_ = x;
}

const Properties::PartialOptional& Properties::
partial () const
{
  return this->partial_;
}

Properties::PartialOptional& Properties::
partial ()
{
  return this->partial_;
}

void Properties::
partial (const PartialType& x)
{
  this->partial_.set (x);
}

void Properties::
partial (const PartialOptional& x)
{
  this->partial_ = x;
}

const Properties::DisabledOptional& Properties::
disabled () const
{
  return this->disabled_;
}

Properties::DisabledOptional& Properties::
disabled ()
{
  return this->disabled_;
}

void Properties::
disabled (const DisabledType& x)
{
  this->disabled_.set (x);
}

void Properties::
disabled (const DisabledOptional& x)
{
  this->disabled_ = x;
}


#include <xsd/cxx/xml/dom/wildcard-source.hxx>

#include <xsd/cxx/xml/dom/parsing-source.hxx>

#include <xsd/cxx/tree/type-factory-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::type_factory_plate< 0, char >
  type_factory_plate_init;
}

// EnvironmentVariables
//

EnvironmentVariables::
EnvironmentVariables (const ClsidType& clsid)
: ::xml_schema::Type (),
  EnvironmentVariable_ (this),
  clsid_ (clsid, this),
  disabled_ (this)
{
}

EnvironmentVariables::
EnvironmentVariables (const EnvironmentVariables& x,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  EnvironmentVariable_ (x.EnvironmentVariable_, f, this),
  clsid_ (x.clsid_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

EnvironmentVariables::
EnvironmentVariables (const ::xercesc::DOMElement& e,
                      ::xml_schema::Flags f,
                      ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  EnvironmentVariable_ (this),
  clsid_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void EnvironmentVariables::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // EnvironmentVariable
    //
    if (n.name () == "EnvironmentVariable" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< EnvironmentVariableType > r (
        EnvironmentVariableTraits::create (i, f, this));

      this->EnvironmentVariable_.push_back (::std::move (r));
      continue;
    }

    break;
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }
}

EnvironmentVariables* EnvironmentVariables::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnvironmentVariables (*this, f, c);
}

EnvironmentVariables& EnvironmentVariables::
operator= (const EnvironmentVariables& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->EnvironmentVariable_ = x.EnvironmentVariable_;
    this->clsid_ = x.clsid_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

EnvironmentVariables::
~EnvironmentVariables ()
{
}

// EnvironmentVariable
//

EnvironmentVariable::
EnvironmentVariable (const PropertiesType& Properties,
                     const ClsidType& clsid,
                     const NameType& name,
                     const UidType& uid)
: ::xml_schema::Type (),
  Properties_ (Properties, this),
  clsid_ (clsid, this),
  name_ (name, this),
  image_ (this),
  changed_ (this),
  uid_ (uid, this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
}

EnvironmentVariable::
EnvironmentVariable (::std::unique_ptr< PropertiesType > Properties,
                     const ClsidType& clsid,
                     const NameType& name,
                     const UidType& uid)
: ::xml_schema::Type (),
  Properties_ (std::move (Properties), this),
  clsid_ (clsid, this),
  name_ (name, this),
  image_ (this),
  changed_ (this),
  uid_ (uid, this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
}

EnvironmentVariable::
EnvironmentVariable (const EnvironmentVariable& x,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  Properties_ (x.Properties_, f, this),
  clsid_ (x.clsid_, f, this),
  name_ (x.name_, f, this),
  image_ (x.image_, f, this),
  changed_ (x.changed_, f, this),
  uid_ (x.uid_, f, this),
  desc_ (x.desc_, f, this),
  bypassErrors_ (x.bypassErrors_, f, this),
  userContext_ (x.userContext_, f, this),
  removePolicy_ (x.removePolicy_, f, this)
{
}

EnvironmentVariable::
EnvironmentVariable (const ::xercesc::DOMElement& e,
                     ::xml_schema::Flags f,
                     ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  Properties_ (this),
  clsid_ (this),
  name_ (this),
  image_ (this),
  changed_ (this),
  uid_ (this),
  desc_ (this),
  bypassErrors_ (this),
  userContext_ (this),
  removePolicy_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, true, false, true);
    this->parse (p, f);
  }
}

void EnvironmentVariable::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  for (; p.more_content (); p.next_content (false))
  {
    const ::xercesc::DOMElement& i (p.cur_element ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    // Properties
    //
    if (n.name () == "Properties" && n.namespace_ ().empty ())
    {
      ::std::unique_ptr< PropertiesType > r (
        PropertiesTraits::create (i, f, this));

      if (!Properties_.present ())
      {
        this->Properties_.set (::std::move (r));
        continue;
      }
    }

    break;
  }

  if (!Properties_.present ())
  {
    throw ::xsd::cxx::tree::expected_element< char > (
      "Properties",
      "");
  }

  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "clsid" && n.namespace_ ().empty ())
    {
      this->clsid_.set (ClsidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      this->name_.set (NameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "image" && n.namespace_ ().empty ())
    {
      this->image_.set (ImageTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "changed" && n.namespace_ ().empty ())
    {
      this->changed_.set (ChangedTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "uid" && n.namespace_ ().empty ())
    {
      this->uid_.set (UidTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "desc" && n.namespace_ ().empty ())
    {
      this->desc_.set (DescTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "bypassErrors" && n.namespace_ ().empty ())
    {
      this->bypassErrors_.set (BypassErrorsTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "userContext" && n.namespace_ ().empty ())
    {
      this->userContext_.set (UserContextTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "removePolicy" && n.namespace_ ().empty ())
    {
      this->removePolicy_.set (RemovePolicyTraits::create (i, f, this));
      continue;
    }
  }

  if (!clsid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "clsid",
      "");
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "name",
      "");
  }

  if (!uid_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "uid",
      "");
  }
}

EnvironmentVariable* EnvironmentVariable::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class EnvironmentVariable (*this, f, c);
}

EnvironmentVariable& EnvironmentVariable::
operator= (const EnvironmentVariable& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->Properties_ = x.Properties_;
    this->clsid_ = x.clsid_;
    this->name_ = x.name_;
    this->image_ = x.image_;
    this->changed_ = x.changed_;
    this->uid_ = x.uid_;
    this->desc_ = x.desc_;
    this->bypassErrors_ = x.bypassErrors_;
    this->userContext_ = x.userContext_;
    this->removePolicy_ = x.removePolicy_;
  }

  return *this;
}

EnvironmentVariable::
~EnvironmentVariable ()
{
}

// Properties
//

Properties::
Properties (const NameType& name,
            const ValueType& value)
: ::xml_schema::Type (),
  action_ (this),
  name_ (name, this),
  value_ (value, this),
  user_ (this),
  partial_ (this),
  disabled_ (this)
{
}

Properties::
Properties (const Properties& x,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::xml_schema::Type (x, f, c),
  action_ (x.action_, f, this),
  name_ (x.name_, f, this),
  value_ (x.value_, f, this),
  user_ (x.user_, f, this),
  partial_ (x.partial_, f, this),
  disabled_ (x.disabled_, f, this)
{
}

Properties::
Properties (const ::xercesc::DOMElement& e,
            ::xml_schema::Flags f,
            ::xml_schema::Container* c)
: ::xml_schema::Type (e, f | ::xml_schema::Flags::base, c),
  action_ (this),
  name_ (this),
  value_ (this),
  user_ (this),
  partial_ (this),
  disabled_ (this)
{
  if ((f & ::xml_schema::Flags::base) == 0)
  {
    ::xsd::cxx::xml::dom::parser< char > p (e, false, false, true);
    this->parse (p, f);
  }
}

void Properties::
parse (::xsd::cxx::xml::dom::parser< char >& p,
       ::xml_schema::Flags f)
{
  while (p.more_attributes ())
  {
    const ::xercesc::DOMAttr& i (p.next_attribute ());
    const ::xsd::cxx::xml::qualified_name< char > n (
      ::xsd::cxx::xml::dom::name< char > (i));

    if (n.name () == "action" && n.namespace_ ().empty ())
    {
      this->action_.set (ActionTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "name" && n.namespace_ ().empty ())
    {
      this->name_.set (NameTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "value" && n.namespace_ ().empty ())
    {
      this->value_.set (ValueTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "user" && n.namespace_ ().empty ())
    {
      this->user_.set (UserTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "partial" && n.namespace_ ().empty ())
    {
      this->partial_.set (PartialTraits::create (i, f, this));
      continue;
    }

    if (n.name () == "disabled" && n.namespace_ ().empty ())
    {
      this->disabled_.set (DisabledTraits::create (i, f, this));
      continue;
    }
  }

  if (!name_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "name",
      "");
  }

  if (!value_.present ())
  {
    throw ::xsd::cxx::tree::expected_attribute< char > (
      "value",
      "");
  }
}

Properties* Properties::
_clone (::xml_schema::Flags f,
        ::xml_schema::Container* c) const
{
  return new class Properties (*this, f, c);
}

Properties& Properties::
operator= (const Properties& x)
{
  if (this != &x)
  {
    static_cast< ::xml_schema::Type& > (*this) = x;
    this->action_ = x.action_;
    this->name_ = x.name_;
    this->value_ = x.value_;
    this->user_ = x.user_;
    this->partial_ = x.partial_;
    this->disabled_ = x.disabled_;
  }

  return *this;
}

Properties::
~Properties ()
{
}

#include <ostream>

#include <xsd/cxx/tree/std-ostream-map.hxx>

namespace _xsd
{
  static
  const ::xsd::cxx::tree::std_ostream_plate< 0, char >
  std_ostream_plate_init;
}

::std::ostream&
operator<< (::std::ostream& o, const EnvironmentVariables& i)
{
  for (EnvironmentVariables::EnvironmentVariableConstIterator
       b (i.EnvironmentVariable ().begin ()), e (i.EnvironmentVariable ().end ());
       b != e; ++b)
  {
    o << ::std::endl << "EnvironmentVariable: " << *b;
  }

  o << ::std::endl << "clsid: " << i.clsid ();
  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const EnvironmentVariable& i)
{
  o << ::std::endl << "Properties: " << i.Properties ();
  o << ::std::endl << "clsid: " << i.clsid ();
  o << ::std::endl << "name: " << i.name ();
  if (i.image ())
  {
    o << ::std::endl << "image: " << *i.image ();
  }

  if (i.changed ())
  {
    o << ::std::endl << "changed: " << *i.changed ();
  }

  o << ::std::endl << "uid: " << i.uid ();
  if (i.desc ())
  {
    o << ::std::endl << "desc: " << *i.desc ();
  }

  if (i.bypassErrors ())
  {
    o << ::std::endl << "bypassErrors: " << *i.bypassErrors ();
  }

  if (i.userContext ())
  {
    o << ::std::endl << "userContext: " << *i.userContext ();
  }

  if (i.removePolicy ())
  {
    o << ::std::endl << "removePolicy: " << *i.removePolicy ();
  }

  return o;
}

::std::ostream&
operator<< (::std::ostream& o, const Properties& i)
{
  if (i.action ())
  {
    o << ::std::endl << "action: " << *i.action ();
  }

  o << ::std::endl << "name: " << i.name ();
  o << ::std::endl << "value: " << i.value ();
  if (i.user ())
  {
    o << ::std::endl << "user: " << *i.user ();
  }

  if (i.partial ())
  {
    o << ::std::endl << "partial: " << *i.partial ();
  }

  if (i.disabled ())
  {
    o << ::std::endl << "disabled: " << *i.disabled ();
  }

  return o;
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (const ::std::string& u,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (const ::std::string& u,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (const ::std::string& u,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      u, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::EnvironmentVariables_ (isrc, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::EnvironmentVariables_ (isrc, h, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is);
  return ::EnvironmentVariables_ (isrc, h, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::EnvironmentVariables_ (isrc, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::auto_initializer i (
    (f & ::xml_schema::Flags::dont_initialize) == 0,
    (f & ::xml_schema::Flags::keep_dom) == 0);

  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::EnvironmentVariables_ (isrc, h, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::std::istream& is,
                       const ::std::string& sid,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
  return ::EnvironmentVariables_ (isrc, h, f, p);
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::xercesc::InputSource& i,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xsd::cxx::tree::error_handler< char > h;

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  h.throw_if_failed< ::xsd::cxx::tree::parsing< char > > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::xercesc::InputSource& i,
                       ::xml_schema::ErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::xercesc::InputSource& i,
                       ::xercesc::DOMErrorHandler& h,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
    ::xsd::cxx::xml::dom::parse< char > (
      i, h, p, f));

  if (!d.get ())
    throw ::xsd::cxx::tree::parsing< char > ();

  return ::std::unique_ptr< ::EnvironmentVariables > (
    ::EnvironmentVariables_ (
      std::move (d), f | ::xml_schema::Flags::own_dom, p));
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (const ::xercesc::DOMDocument& doc,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties& p)
{
  if (f & ::xml_schema::Flags::keep_dom)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

    return ::std::unique_ptr< ::EnvironmentVariables > (
      ::EnvironmentVariables_ (
        std::move (d), f | ::xml_schema::Flags::own_dom, p));
  }

  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (n.name () == "EnvironmentVariables" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::EnvironmentVariables > r (
      ::xsd::cxx::tree::traits< ::EnvironmentVariables, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "EnvironmentVariables",
    "");
}

::std::unique_ptr< ::EnvironmentVariables >
EnvironmentVariables_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                       ::xml_schema::Flags f,
                       const ::xml_schema::Properties&)
{
  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
    ((f & ::xml_schema::Flags::keep_dom) &&
     !(f & ::xml_schema::Flags::own_dom))
    ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
    : 0);

  ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
  const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

  const ::xsd::cxx::xml::qualified_name< char > n (
    ::xsd::cxx::xml::dom::name< char > (e));

  if (f & ::xml_schema::Flags::keep_dom)
    doc.setUserData (::xml_schema::dom::tree_node_key,
                     (c.get () ? &c : &d),
                     0);

  if (n.name () == "EnvironmentVariables" &&
      n.namespace_ () == "")
  {
    ::std::unique_ptr< ::EnvironmentVariables > r (
      ::xsd::cxx::tree::traits< ::EnvironmentVariables, char >::create (
        e, f, 0));
    return r;
  }

  throw ::xsd::cxx::tree::unexpected_element < char > (
    n.name (),
    n.namespace_ (),
    "EnvironmentVariables",
    "");
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

