name: gpui-build

on:
  workflow_call:
    inputs:
      distr:
        description: "Linux distribution"
        type: string
        required: true
      artifact:
        description: "Artifact"
        type: string
        required: true
      architecture:
        description: "Architecture"
        type: string
        required: true

jobs:
  gpui-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alt-version: [ { dist: "alt:sisyphus", artifact: "sisyphus" } ]
        architecture: [ amd64 ]
    steps:
      - if: ${{ inputs.architecture == 'i386' }}
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest --platform linux/i386
          docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app \
          ghcr.io/${{ github.repository }}:latest --platform linux/i386

      - if: ${{ inputs.architecture == 'amd64' }}
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app \
          ghcr.io/${{ github.repository }}:latest

      - uses: actions/upload-artifact@v3
        with:
          name: gpui-${{ inputs.artifact }}-${{ inputs.architecture }}
          path: /home/builder2/RPM/RPMS/x86_64/
