name: gpui-build

on:
  workflow_call:
    inputs:
      distr:
        description: "Linux distribution"
        type: string
        required: true
      artifact:
        description: "Artifact"
        type: string
        required: true
      architecture:
        description: "Architecture"
        type: string
        required: true

jobs:
  gpui-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest
          docker run --privileged=true --name gpui-build-${{ inputs.architecture }} -i --log-driver=none \
          -a stdin -a stdout -a stderr -v "$(pwd)":/app ghcr.io/${{ github.repository }}:latest \
          --platform linux/${{ inputs.architecture }}

      - name: Extract packages
        run: |
          docker cp gpui-build-${{ inputs.architecture }}:/home/builder2/RPM/RPMS/ "$(pwd)/packages"

      - name: Upload fresh RPM packages
        uses: actions/upload-artifact@v3
        with:
          name: gpui-${{ inputs.artifact }}-${{ inputs.architecture }}
          path: ${{ github.workspace }}/packages
