name: gpui-build-container

on:
  workflow_call:
    inputs:
      distr:
        description: "Linux distribution"
        type: string
        required: true
      architecture:
        description: "Architecture"
        type: string
        required: true

jobs:
  gpui-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set output variables
        id: vars
        run: |
          user_id="$(id -u)"
          group_id="$(id -g)"
          echo "user_id=$user_id" >> $GITHUB_OUTPUT
          echo "group_id=$group_id" >> $GITHUB_OUTPUT

      - name: Build and push container to the registry
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}-${{ inputs.architecture }}:${{ github.run_number }}
            ghcr.io/${{ github.repository }}-${{ inputs.architecture }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ inputs.architecture }}
          build-args: |
            DISTR=${{ inputs.distr }}
            ARCH=${{ inputs.architecture }}
            USER_ID=${{ steps.vars.outputs.user_id }}
            GROUP_ID=${{ steps.vars.outputs.group_id }}
