name: gpui-build-container

on:
  workflow_call:
    inputs:
      alt-version:
        description: "ALT Linux version"
        type: string
        required: true
      architecture:
        description: "Architecture"
        type: string
        required: true

jobs:
  gpui-build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
            ghcr.io/${{ github.repository }}:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DISTR=${{ inputs.alt-version.dist }}
            ARCH=${{ inputs.architecture }}
            USER_ID=1001
            GROUP_ID=121
